FROM php:8.2-apache

# Habilita mod rewrite (importante para sistemas PHP)
RUN a2enmod rewrite

# Copia arquivos do projeto para o servidor Apache
COPY src/ /var/www/html/

# Ajusta permissões
RUN chown -R www-data:www-data /var/www/html